# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/hardware/network/broadcom-43xx.nix")
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = lib.mkDefault
    { device = "/dev/disk/by-uuid/0f6c3a33-69cd-4aa1-b17e-99d3a9f8e686";
      fsType = "btrfs";
      options = [ "subvol=@" ];
    };

  fileSystems."/nix" = lib.mkDefault
    { device = "/dev/disk/by-uuid/0f6c3a33-69cd-4aa1-b17e-99d3a9f8e686";
      fsType = "btrfs";
      options = [ "subvol=@nix" ];
    };

  fileSystems."/home" = lib.mkDefault
    { device = "/dev/disk/by-uuid/0f6c3a33-69cd-4aa1-b17e-99d3a9f8e686";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  fileSystems."/boot" = lib.mkDefault
    { device = "/dev/disk/by-uuid/F39B-A446";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = lib.mkDefault
    [ { device = "/dev/disk/by-uuid/df6d66e7-03f8-49bd-b908-6e6442667071"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
